language: python
python:
  - "3.7"
# command to install dependencies
sudo: false
before_install:
  - sudo apt-get install ncbi-blast+
install:
  - pip install coveralls pytest-cov==2.6 pytest==3.2.3
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov genome_collector --cov-report term-missing

after_success:
  - coveralls
